### PR TITLE
kappa_air replaced with cp/cv

### PR DESCRIPTION
**Pull request by NicBuettner**
kappa_air in ad_temp and constants replaced with cp_air and cv_air

### CODE REVIEW

**Review by fabrivelas — COMMENTED** [review]
@NicBuettner would it make sense to leave the definition for kappa_air with an additional line
kappa_air = c_p_air / c_v_air in _custom_defined.py?
Then you would also avoid changing ad_temp.py.

**Comment by NicBuettner** [comment]
@fabrivelas I guess it depends on how we want to set up the constants lists. We should discuss if we put in all constants or leave out the ones which are derived from others.

**Comment by ucyo** [comment]
I think interdependencies should be allowed. The recommendation from @fabrivelas is a good one I think ...

**Comment by ucyo** [comment]
Information for the heat capacity: https://en.wikipedia.org/wiki/Heat_capacity_ratio

**Comment by NicBuettner** [comment]
@ucyo, @fabrivelas I gave the constant two names now: gamma_air and adiabatic_index_air

**Pull request merged**
