### PR TITLE
new method vapour_pres_ice.py

### PR DESCRIPTION
**Pull request by NicBuettner**

### CODE REVIEW

**Comment by ucyo** [comment]
👋🏼 Hey, awesome!! New features!! 🚀 
Unfortunately it seems like there seems to be a diverge from your main branch and the `imktk` library. Could you get changes from the upstream and merge them to your master? But I will show this on Wednesday :)

**Comment by NicBuettner** [comment]
I did fetch the upstream, but for some reason it tells me that I'm ahead of the imktk library. But these are only the commits I made for the last pull request. So I have no idea how to fix this.

**Comment by NicBuettner** [comment]
Do you have any sugsestions?

**Comment by ucyo** [comment]
You could (1) squash the commits to a single commit and (2) force push to the repository. The first step ist described in [here in the subsection _Squashing multiple commits together_](https://www.sublimemerge.com/blog/sublime-merge-tips-editing-git-commits). The second step is described [in this Q&A in the second post](https://forum.sublimetext.com/t/force-push-with-lease/39252/2).

**Comment by NicBuettner** [comment]
I ran into new problems 😕 I rebased my repository to the newest commits you made yesterday. Now the static analysis test is failing for the anomalies file... And I tried to squash the commits but I got the message: "Error: only commits reachable from HEAD can be modified". I don't understand why these commits wouldn't be reachable...

**Comment by ucyo** [comment]
I fixed the main branch of imktk. Can you fetch+merge the changes and include them here? That should fix the instance

**Comment by NicBuettner** [comment]
Okay, I merged it. At least the checks passed now :) But I still can't squash the commits in sublime merge...

**Comment by ucyo** [comment]
Progress. Interesting that you can not squash the commits... Let me check on my side

**Comment by ucyo** [comment]
Nice. I think I know the issue. The merge commits are causing discrepancies in the history of the files. That is the reason of the conflicts. But I have a fix :)

For the fix you will to create a temporary branch and cherry pick changes to the master. Before we start, be sure that you have both repositories at the latest stages. The upstream repository linking to imktoolkit/imktoolkit and your own repository 😅 

Information about the linked repositories you can get via `git remote -v` and the output should be like the following

```shell
> git remote -v                                                     
origin	git@github.com:NicBuettner/imk-toolkit.git (fetch)
origin	git@github.com:NicBuettner/imk-toolkit.git (push)
upstream	git@github.com:imk-toolkit/imk-toolkit.git (fetch)
upstream	git@github.com:imk-toolkit/imk-toolkit.git (push)
```
The latest changes you can get with 
``` shell
git fetch --all --prune
```
This concludes the preparation. Now to the actual fixes:

1. Create a temporary branch at `origin/master`. This will gurantee that we can always return to our starting point and eases our minds 😸 `git checkout master` and `git checkout -b tmp`
2. Then you switch back to master and do a hard reset to the tag `v0.1.9-rc.1` with the command `git checkout master` and `git reset --hard v0.1.9-rc.1`
3. Now you can cherry-pick the changes you committed. There are two commits you want to add. These are  the commits 05bc97f6b2449dad03807805b32424d9b08ae26d and ea254624d9f03c63d8580b37e70023bf4cbb11e7. That can be done via the following commands: `git cherry-pick 05bc97f6b2449dad03807805b32424d9b08ae26d` and 
`git cherry-pick ea254624d9f03c63d8580b37e70023bf4cbb11e7`. This concludes the changes needed. 
4. For the final step we need to rebase the your master onto the upstream master. You can do this by `git rebase upstream/master` 

Then it is done. Force push to your repository via `git push --force` and I should be able to merge the PR 🚀

**Comment by NicBuettner** [comment]
🎉  it worked :) thank you! Turns out I hadn't set the imk-toolkit/imk-toolkit as upstream... What's the best way to avoid these problems in the future?

**Comment by ucyo** [comment]
Following two key principles should avoid any problems. 

1. Always have an `upstream` remote repository setup. This helps getting changes from the main repository and guarantees that you are up to date. Using `git fetch --all --prune` will get you a perfect replication of the remote sites on your local machine
2. Try to avoid using `git merge` as much as possible, instead opt to `git rebase`. Rebasing helps to get a linear timeline.

**Pull request merged**
